export let  products = 
  [
    { "id": 1, "title": "Salmón", "category": "mar", "description": "¡Deléitate con la frescura y la salud que ofrece nuestro Salmón! Criado en las aguas más puras, este pescado es una fuente de ácidos grasos Omega-3 esenciales para tu bienestar. Disfruta de su sabor exquisito y su textura delicada. Perfecto para una cena gourmet o una comida nutritiva.", "price": 15000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306078/SALMON_b73cmh.jpg" },
    { "id": 2, "title": "Atún", "category": "mar", "description": "¡Descubre el sabor inigualable del océano con nuestro Atún fresco! Capturado en su punto óptimo, nuestro Atún es una explosión de frescura y delicia en cada bocado. Rico en proteínas y bajo en grasas, es la elección perfecta para una dieta equilibrada y sabrosa.", "price": 3000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306077/ATUN_bwkwqk.jpg" },
    { "id": 3, "title": "Bacalao", "category": "mar", "description": "¡Sumérgete en el sabor único de nuestro Bacalao fresco! Proveniente de las aguas más cristalinas, nuestro Bacalao es una delicia para los amantes del pescado. Su carne tierna y su sabor suave te conquistarán en cada bocado. Perfecto para platos tradicionales o creaciones culinarias más audaces.", "price": 4500, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306078/bacalao_gvreut.jpg" },
    { "id": 4, "title": "Lubina", "category": "mar", "description": "¡Eleva tus platos con la exquisitez de nuestra Lubina fresca! Criada con cuidado y pasión, nuestra Lubina es un verdadero manjar para los paladares más exigentes. Con su carne firme y su sabor delicado, es la estrella indiscutible de cualquier mesa. Prepárala a la parrilla, al horno o como prefieras y déjate sorprender.", "price": 5000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306077/lubina_n6clxq.jpg" },
    { "id": 5, "title": "Merluza", "category": "mar", "description": "¡Disfruta de la frescura y la nutrición de nuestra Merluza fresca! Capturada en aguas prístinas, nuestra Merluza es una fuente de proteínas de alta calidad y nutrientes esenciales. Con su sabor suave y su textura delicada, es una opción versátil para todo tipo de preparaciones culinarias. Atrévete a explorar nuevos sabores con nuestra Merluza premium.", "price": 3000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306078/merluza_tgwcpe.jpg" },
    { "id": 6, "title": "Sardinas", "category": "mar", "description": "¡Déjate seducir por la autenticidad de nuestras Sardinas frescas! Capturadas en su mejor momento, nuestras Sardinas son una explosión de sabor y frescura en cada lata. Con su carne jugosa y su sabor característico, son el complemento perfecto para tus ensaladas, pastas o simplemente para disfrutar solas. Descubre el placer de lo simple con nuestras Sardinas de calidad premium.", "price": 2000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306078/sardina_vsi6tq.jpg" },
    { "id": 7, "title": "Pulpo", "category": "mariscos", "description": "¡Embárcate en un viaje de sabores con nuestro Pulpo fresco y tierno! Recolectado con cuidado y preparado con maestría, nuestro Pulpo es una experiencia gastronómica que no querrás perderte. Con su textura suave y su sabor inconfundible, es la opción ideal para una cena memorable con amigos o familiares. Atrévete a sorprender y conquista el paladar de todos con nuestro Pulpo de calidad premium.", "price": 9000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306078/pulpo_ocqdrx.jpg" },
    { "id": 8, "title": "Calamares", "category": "mariscos", "description": "¡Disfruta del sabor del mar con nuestros Calamares frescos y deliciosos! Capturados en aguas cristalinas y preparados con esmero, nuestros Calamares son una delicia para los amantes de los frutos del mar. Con su textura tierna y su sabor suave, son el complemento perfecto para tus platos favoritos. Prepáralos fritos, a la plancha o como prefieras y déjate sorprender por su frescura incomparable.", "price": 12000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306077/calamares_s6s7pq.jpg" },
    { "id": 9, "title": "Camarones", "category": "mariscos", "description": "¡Déjate tentar por la suculencia de nuestros Camarones frescos y jugosos! Capturados en su mejor momento, nuestros Camarones son una explosión de sabor y frescura en cada bocado. Con su carne tierna y su sabor dulce, son el ingrediente perfecto para tus platos favoritos. Atrévete a elevar tus recetas con la calidad premium de nuestros Camarones.", "price": 7000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306077/camarones_qhphf4.jpg" },
    { "id": 10, "title": "Langostinos", "category": "mariscos", "description": "¡Disfruta de la exquisitez de nuestros Langostinos frescos y exquisitos! Recolectados con cuidado y seleccionados con esmero, nuestros Langostinos son una verdadera delicatessen para los amantes de los mariscos. Con su carne firme y su sabor dulce, son el complemento perfecto para tus platos más sofisticados. Prepáralos a la parrilla, al vapor o como prefieras y sorprende a tus invitados con la frescura y la calidad de nuestros Langostinos premium.", "price": 6000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306077/langostinos_l9w0ji.jpg" },
    { "id": 11, "title": "Almejas", "category": "mariscos", "description": "¡Déjate seducir por la intensidad de nuestro Almejas frescas y llenas de sabor! Recolectadas en aguas cristalinas y seleccionadas con cuidado, nuestras Almejas son una explosión de frescura y sabor en cada bocado. Con su textura tierna y su sabor intenso, son el complemento perfecto para tus platos de mariscos favoritos. Atrévete a descubrir la calidad premium de nuestras Almejas y sorprende a tu paladar.", "price": 1300, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306076/almejas_rb6btn.jpg" },
    { "id": 12, "title": "Ostras", "category": "mariscos", "description": "¡Sumérgete en la elegancia de nuestras Ostras frescas y suculentas! Recolectadas con cuidado y preparadas con maestría, nuestras Ostras son una verdadera delicia para los amantes de los mariscos. Con su sabor único y su textura delicada, son el complemento perfecto para una cena elegante o una ocasión especial. Atrévete a sorprender con la frescura y la calidad de nuestras Ostras premium.", "price": 3000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306077/ostras_pyvlxs.jpg" },
    { "id": 13, "title": "Pez espada", "category": "mar", "description": "¡Descubre la versatilidad y la frescura de nuestro Pez espada fresco! Capturado en aguas cristalinas, nuestro Pez espada es una opción exquisita para los amantes del pescado. Con su carne firme y su sabor delicado, es perfecto para todo tipo de preparaciones culinarias. Atrévete a explorar nuevos sabores y disfruta de la calidad premium de nuestro Pez espada.", "price": 6000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306078/pez_espada_bncprh.jpg" },
    { "id": 14, "title": "Trucha", "category": "rio", "description": "¡Disfruta de la frescura y la salud con nuestra Trucha fresca! Criada en aguas puras y alimentada de forma natural, nuestra Trucha es una opción nutritiva y deliciosa para toda la familia. Con su carne tierna y su sabor suave, es perfecta para platos tanto tradicionales como innovadores. Atrévete a probar la calidad premium de nuestra Trucha y descubre un mundo de sabores.", "price": 5000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306078/trucha_qvixws.jpg" },
    { "id": 15, "title": "Dorado", "category": "rio", "description": "¡Déjate conquistar por la frescura y el sabor de nuestro Dorado fresco! Criado en aguas limpias y alimentado de forma natural, nuestro Dorado es una opción deliciosa y saludable para tus comidas. Con su carne firme y su sabor delicado, es perfecto para todo tipo de preparaciones culinarias. Atrévete a disfrutar de la calidad premium de nuestro Dorado y sorprende a tu paladar.", "price": 5000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306076/dorado_vuptbq.jpg" },
    { "id": 16, "title": "Cangrejo", "category": "mariscos", "description": "¡Sumérgete en el sabor del mar con nuestro Cangrejo fresco y sabroso! Recolectado con cuidado y preparado con esmero, nuestro Cangrejo es una auténtica delicia para los amantes de los mariscos. Con su carne tierna y su sabor suave, es perfecto para todo tipo de recetas. Prepáralo a la parrilla, en ensaladas o como prefieras y déjate sorprender por su frescura incomparable.", "price": 2800, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306076/cangrejo_v39l2z.jpg" },
    { "id": 17, "title": "Anchoas", "category": "enlatados", "description": "¡Disfruta del sabor auténtico del mar con nuestras Anchoas en conserva de alta calidad! Capturadas en su punto óptimo, nuestras Anchoas son una explosión de sabor y frescura en cada lata. Con su textura firme y su sabor intenso, son el complemento perfecto para tus ensaladas, pizzas o aperitivos favoritos. Atrévete a descubrir la calidad premium de nuestras Anchoas y disfruta del auténtico sabor del Mediterráneo.", "price": 8000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306076/anchoas_at4if7.jpg" },
    { "id": 18, "title": "Salmón ahumado", "category": "mar", "description": "¡Eleva tus sentidos con la exquisitez de nuestro Salmón ahumado premium! Elaborado con los mejores ingredientes y ahumado con madera de calidad, nuestro Salmón ahumado es una experiencia gastronómica única. Con su sabor intenso y su textura delicada, es perfecto para picoteos, desayunos o como parte de platos más elaborados. Atrévete a descubrir la calidad premium de nuestro Salmón ahumado y déjate seducir por su sabor inigualable.", "price": 18000, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306078/salmon_ahumado_pybzsp.jpg" },
    { "id": 19, "title": "Sardina", "category": "enlatados", "description": "¡Descubre la comodidad y el sabor con nuestras Sardinas en lata en aceite de oliva! Seleccionadas con cuidado y envasadas con esmero, nuestras Sardinas son una opción práctica y deliciosa para tus comidas. Con su carne jugosa y su sabor característico, son perfectas para tus ensaladas, tostadas o como aperitivo. Atrévete a disfrutar del sabor auténtico del mar con nuestras Sardinas en lata.", "price": 3200, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306078/sardina_en_latasa_dvn6bl.jpg" },
    { "id": 20, "title": "Atún", "category": "enlatados", "description": "¡Disfruta de la practicidad y el sabor con nuestro Atún en lata en su jugo! Elaborado con los mejores ingredientes y envasado con cuidado, nuestro Atún en lata es una opción deliciosa y versátil para tus comidas. Con su carne tierna y su sabor suave, es perfecto para ensaladas, pastas o como relleno de tus sandwiches favoritos. Atrévete a descubrir la comodidad y la calidad de nuestro Atún en lata.", "price": 1500, "img": "https://res.cloudinary.com/dpvaf6koo/image/upload/v1713306076/atun_lata_yzjmtf.jpg" }
  ]
  